'''If we list all the natural numbers below 10 
that are multiples of 3 or 5, we get 3, 5, 6 and 9.
 The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.'''
 
# a=0
# sum=0
# while a<1000:
#     if a%3==0 or a%5==0:
#         sum+=a
#     a+=1
# print(sum)

'''Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.
'''
# i=0
# a=0
# b=1
# n=0
# sum=0
# while i<4000000:
#     c=a+b
#     a=b
#     b=c
#     if c%2==0:
#         sum+=c
#     if a>4000000:
#         break
#     i+=1
# print(sum)

''' The prime factors of 13195 are 5, 7, 13 and 29.
 What is the largest prime factor of the number 600851475143 ?'''


# n = 600851475143
# i = 2
# while i * i < n:
#      while n % i == 0:
#          n = n // i
#      i = i + 1
# print(n)

# 

# fruit_list =  ["apple", "mango", "apple", "banana", "mango", "apple", "grapes"]

# unique_list = []
# [unique_list.append(n) for n in fruit_list if n not in unique_list]
# print(unique_list)


'''  By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
 What is the 10001st prime number?'''

# n = int(input("Enter a number : "))
# c = 2
# while n!=0:
#   for i in range(2,c):
#     if c%i==0:
#       break
#   else:  
#     b=c  
#     n-=1
#   c+=1  
# print(b)



'''A palindromic number reads the same both ways.
 The largest palindrome made from the product of two 2-digit 
 numbers is 9009 = 91 × 99. Find the largest palindrome made from the product of two 3-digit numbers.'''


# n=0
# for i in range(999,10,-1):
#     for j in range(i,10,-1):
#         a=i*j
#         if a>n:
#             b=str(i*j)
#             if b==b[::-1]:
#                 n=i*j
# print(n)



'''   2520 is the smallest number that can be divided by each of the numbers
 from 1 to 10 without any remainder. What is the smallest positive number
  that is evenly divisible by all of the numbers from 1 to 20?'''



# flag=0
# i=2520
# while i>0:
#     for j in range(11,21):
#         if i%j==0:
#             flag+=1
#     if flag==10:
#         print(i)
#         break
#     flag=0
#     i+=20


'''A Pythagorean triplet is a set of three natural numbers, a < b < c,

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.
'''

# for a in range(1,1001):
#     for b in range(1,1001):A
#         c=1000-a-b
#         if c<0:
#             break
#         if a<b<c and a*a+b*b==c*c:
#             print(a*b*c)
#             print(a,b,c)



'''Find the sum of all the primes below two million.'''